### ISSUE TITLE
"Cannot find module "./../config"

### ISSUE THREAD

**Issue by LudwikJaniuk** [datasektionen/gloo#6]
When I try running, this is the error I get. It comes from express.js, but changing the import to "./config" (in case of caching, I guess) does not help. Assuming this has to do with your latest changes @macfeaster, is this the expected behavior? And how do I actually launch?

**Comment by macfeaster** [comment]
This is related to the new setup system: the config file and template directories included in this repo are just examples; in a deployed app you would provide your own. Thus, `config.example.js` should be renamed `config.js`, and `templates_example` should be renamed `templates`.

This is expected behavior and intentional. It will be documented, but isn't yet, hence the confusion - my apologies.

**Comment by LudwikJaniuk** [comment]
Allright, thanks. AS long as it gets added to th README, we're golden.
